### PR TITLE
adds non orthogonal line drawing

### PR DESCRIPTION
**Pull request by m-abboud**
See attached zip for sample pdf with a bunch of diagonal lines and the html output this pull request gives.
[pdf-lines-sample.zip](https://github.com/radkovo/Pdf2Dom/files/241543/pdf-lines-sample.zip)

### CODE REVIEW

**Comment by radkovo** [comment]
Many thanks for your pull requests. They seem both great for the first look. I review them more thoroughly and I will merge asap (within a few days).

**Comment by meese** [comment]
No problem! And thank you for making this awesome library! Only decent open source PDF -> HTML converter I could find for a side web project I was doing. (but have since abandoned my project that was using this and having a little more fun just working on this library itself lol)

**Comment by meese** [comment]
added commmit for CSSBoxTree support too

**Comment by radkovo** [comment]
All merged, thank you very much!

**Comment by radkovo** [comment]
BTW, I come across a minor problem when drawing vertical lines (`getAngleDegrees()` returned NaN) so I added some optimizations for drawing horizontal and vertical lines with no rotations.

**Comment by m-abboud** [comment]
Oops sorry about that! Thought I had added horz/vert lines to my test doc, was having trouble making perfectly straight lines in my pdf editor though..

**Comment by radkovo** [comment]
No problem, btw thanks for the tests you provided. I have made some changes in the test PDF loading (using resources) and configured the project for TravisCI so now the tests are run automatically.

**Comment by m-abboud** [comment]
Sweet! And that's bizarre how that one test is giving different color results on different platforms, I have no idea why either (fillRenderingModeText_outputIsFilledWithNoOutline is the test)

**Comment by radkovo** [comment]
I didn't have time for more detailed debugging but my guess is: is it possible that the color is specified using a different color model in the testing PDF and some rounding-related issues occur during the conversion to RGB?

**Pull request merged**
